// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service1.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InterfaceRequest struct {
	InterfaceName        string   `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`
	RouterName           string   `protobuf:"bytes,2,opt,name=routerName,proto3" json:"routerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceRequest) Reset()         { *m = InterfaceRequest{} }
func (m *InterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*InterfaceRequest) ProtoMessage()    {}
func (*InterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c160ae52f4d11313, []int{0}
}

func (m *InterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceRequest.Unmarshal(m, b)
}
func (m *InterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceRequest.Marshal(b, m, deterministic)
}
func (m *InterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceRequest.Merge(m, src)
}
func (m *InterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_InterfaceRequest.Size(m)
}
func (m *InterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceRequest proto.InternalMessageInfo

func (m *InterfaceRequest) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *InterfaceRequest) GetRouterName() string {
	if m != nil {
		return m.RouterName
	}
	return ""
}

type InterfaceReply struct {
	ReceivedBytes        int64    `protobuf:"varint,1,opt,name=receivedBytes,proto3" json:"receivedBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceReply) Reset()         { *m = InterfaceReply{} }
func (m *InterfaceReply) String() string { return proto.CompactTextString(m) }
func (*InterfaceReply) ProtoMessage()    {}
func (*InterfaceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c160ae52f4d11313, []int{1}
}

func (m *InterfaceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceReply.Unmarshal(m, b)
}
func (m *InterfaceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceReply.Marshal(b, m, deterministic)
}
func (m *InterfaceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceReply.Merge(m, src)
}
func (m *InterfaceReply) XXX_Size() int {
	return xxx_messageInfo_InterfaceReply.Size(m)
}
func (m *InterfaceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceReply.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceReply proto.InternalMessageInfo

func (m *InterfaceReply) GetReceivedBytes() int64 {
	if m != nil {
		return m.ReceivedBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*InterfaceRequest)(nil), "proto.InterfaceRequest")
	proto.RegisterType((*InterfaceReply)(nil), "proto.InterfaceReply")
}

func init() { proto.RegisterFile("proto/service1.proto", fileDescriptor_c160ae52f4d11313) }

var fileDescriptor_c160ae52f4d11313 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x35, 0xd4, 0x03, 0x73, 0x85, 0x58, 0xc1,
	0x94, 0x52, 0x04, 0x97, 0x80, 0x67, 0x5e, 0x49, 0x6a, 0x51, 0x5a, 0x62, 0x72, 0x6a, 0x50, 0x6a,
	0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x0a, 0x17, 0x6f, 0x26, 0x4c, 0xcc, 0x2f, 0x31, 0x37, 0x55,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x55, 0x50, 0x48, 0x8e, 0x8b, 0xab, 0x28, 0xbf, 0xb4,
	0x24, 0xb5, 0x08, 0xac, 0x84, 0x09, 0xac, 0x04, 0x49, 0x44, 0xc9, 0x8c, 0x8b, 0x0f, 0xc9, 0xe4,
	0x82, 0x9c, 0x4a, 0x90, 0xb9, 0x45, 0xa9, 0xc9, 0xa9, 0x99, 0x65, 0xa9, 0x29, 0x4e, 0x95, 0x25,
	0xa9, 0xc5, 0x60, 0x73, 0x99, 0x83, 0x50, 0x05, 0x8d, 0x66, 0x31, 0x22, 0x39, 0x29, 0x18, 0xe2,
	0x68, 0x21, 0x17, 0x2e, 0x01, 0xf7, 0xd4, 0x92, 0x20, 0x64, 0x85, 0x42, 0xe2, 0x10, 0x9f, 0xe8,
	0xa1, 0xbb, 0x5f, 0x4a, 0x14, 0x53, 0xa2, 0x20, 0xa7, 0x52, 0x89, 0x41, 0xc8, 0x81, 0x8b, 0xc7,
	0x3d, 0xb5, 0x24, 0x38, 0x35, 0xaf, 0x84, 0x4c, 0x13, 0x9c, 0x64, 0xa3, 0xa4, 0x53, 0x2b, 0x12,
	0x73, 0x0b, 0x72, 0x52, 0xf5, 0x92, 0xf3, 0x73, 0xf5, 0xc1, 0xaa, 0x4a, 0x2a, 0x0b, 0x52, 0x21,
	0xac, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x41, 0x44, 0x69, 0x5f, 0x73,
	0x01, 0x00, 0x00,
}
